# Generated by Django 5.0 on 2024-02-10 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('programme_name', models.CharField(max_length=255, unique=True)),
                ('Cluster', models.CharField(max_length=255)),
                ('Cluster_subject_1', models.CharField(max_length=255)),
                ('Cluster_subject_2', models.CharField(max_length=255)),
                ('Cluster_subject_3', models.CharField(max_length=255)),
                ('Cluster_subject_4', models.CharField(max_length=255)),
                ('Minimum_subject_1', models.CharField(max_length=255)),
                ('Minimum_subject_1_grade', models.CharField(max_length=255)),
                ('Minimum_subject_2', models.CharField(max_length=255)),
                ('Minimum_subject_2_grade', models.CharField(max_length=255)),
                ('Minimum_subject_3', models.CharField(max_length=255)),
                ('Minimum_subject_3_grade', models.CharField(max_length=255)),
                ('Minimum_subject_4', models.CharField(max_length=255)),
                ('Minimum_subject_4_grade', models.CharField(max_length=255)),
                ('Minimum_Mean_Grade', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.IntegerField(unique=True)),
                ('alias', models.CharField(max_length=255, unique=True)),
                ('IName', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=255)),
                ('institution_type', models.CharField(max_length=255)),
                ('Parent_Ministry', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('Programme_Code', models.IntegerField(primary_key=True, serialize=False)),
                ('Programme_Name_in_campus', models.CharField(max_length=255)),
                ('Year_1_Programme_cost', models.CharField(max_length=255)),
                ('_2022_cut_off', models.CharField(max_length=255)),
                ('_2021_cut_off', models.CharField(max_length=255)),
                ('_2020_cut_off', models.CharField(max_length=255)),
                ('Programme_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('Iname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.institution')),
            ],
        ),
    ]
